.TH checkrhosts 8 "January 19, 1997" "" "Linux Users Manual"
.SH NAME
checkrhosts \- program to check the users .rhosts files for
security problems
.SH SYNOPSIS
.B checkrhosts
.SH DESCRIPTION
The
.B checkrhosts
program will check the users .rhosts files for any potential
security problems. It will show which .rhosts files are
insecure and gives a short discription why the .rhosts is insecure
and how this problem can be fixed.
.SH FILES
~/.rhosts
.SH AUTHOR
Peter Tobias <tobias@debian.org>
